version: '3'

services:
  redis:
    image: redis:7
    container_name: master
    ports:
      - "6379:6379"
    volumes:
      - ./bkp:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"] 

